path=%QT5_ROOT%\msvc2015_64\bin
moc -o generated/moc_AboutDialog.cpp AboutDialog.h
moc -o generated/moc_Aperture.cpp Aperture.h
moc -o generated/moc_ApertureWidget.cpp ApertureWidget.h
moc -o generated/moc_AppearanceDockWidget.cpp AppearanceDockWidget.h
moc -o generated/moc_AppearanceSettingsWidget.cpp AppearanceSettingsWidget.h
moc -o generated/moc_Background.cpp Background.h
moc -o generated/moc_BackgroundWidget.cpp BackgroundWidget.h
moc -o generated/moc_Camera.cpp Camera.h
moc -o generated/moc_CameraDockWidget.cpp CameraDockWidget.h
moc -o generated/moc_CameraWidget.cpp CameraWidget.h
moc -o generated/moc_Controls.cpp Controls.h
moc -o generated/moc_Film.cpp Film.h
moc -o generated/moc_FilmWidget.cpp FilmWidget.h
moc -o generated/moc_Focus.cpp Focus.h
moc -o generated/moc_FocusWidget.cpp FocusWidget.h
moc -o generated/moc_HardwareWidget.cpp HardwareWidget.h
moc -o generated/moc_Histogram.cpp Histogram.h
moc -o generated/moc_HttpGet.cpp HttpGet.h
moc -o generated/moc_Light.cpp Light.h
moc -o generated/moc_Lighting.cpp Lighting.h
moc -o generated/moc_LightingDockWidget.cpp LightingDockWidget.h
moc -o generated/moc_LightingWidget.cpp LightingWidget.h
moc -o generated/moc_LightsWidget.cpp LightsWidget.h
moc -o generated/moc_LightWidget.cpp LightWidget.h
moc -o generated/moc_LoadSettingsDialog.cpp LoadSettingsDialog.h
moc -o generated/moc_LogDockWidget.cpp LogDockWidget.h
moc -o generated/moc_Logger.cpp Logger.h
moc -o generated/moc_LogWidget.cpp LogWidget.h
moc -o generated/moc_MainWindow.cpp MainWindow.h
moc -o generated/moc_Node.cpp Node.h
moc -o generated/moc_NodePropertiesWidget.cpp NodePropertiesWidget.h
moc -o generated/moc_NodeSelectionWidget.cpp NodeSelectionWidget.h
moc -o generated/moc_Preset.cpp Preset.h
moc -o generated/moc_PresetsWidget.cpp PresetsWidget.h
moc -o generated/moc_Projection.cpp Projection.h
moc -o generated/moc_ProjectionWidget.cpp ProjectionWidget.h
moc -o generated/moc_RenderThread.cpp RenderThread.h
moc -o generated/moc_SettingsDockWidget.cpp SettingsDockWidget.h
moc -o generated/moc_StartupDialog.cpp StartupDialog.h
moc -o generated/moc_StatisticsDockWidget.cpp StatisticsDockWidget.h
moc -o generated/moc_StatisticsWidget.cpp StatisticsWidget.h
moc -o generated/moc_Status.cpp Status.h
moc -o generated/moc_TransferFunction.cpp TransferFunction.h
moc -o generated/moc_TransferFunctionView.cpp TransferFunctionView.h
moc -o generated/moc_TransferFunctionWidget.cpp TransferFunctionWidget.h
moc -o generated/moc_UpdateWidget.cpp UpdateWidget.h
moc -o generated/moc_VtkWidget.cpp VtkWidget.h